Fix a flaky test by cleaning a polluted state.
pythological/kanren pull request #42
Opened 2021-11-15 17:50 UTC by sturmianseq

# What is the purpose of the change
This PR is to fix a flaky test `tests/test_assoccomm.py::test_eq_assoccomm`,  which can fail after running `tests/test_assoccomm.py::test_assoccomm_objects`, but passes when it is run in isolation.

# Reproduce the test failure
Run the following command:
```
python -m pytest tests/test_assoccomm.py::test_assoccomm_objects tests/test_assoccomm.py::test_eq_assoccomm
```
# Expected Result
`tests/test_assoccomm.py::test_eq_assoccomm` should pass after running `tests/test_assoccomm.py::test_assoccomm_objects`.

# Actual Result
```
FAILED tests/test_assoccomm.py::test_eq_assoccomm - TypeError: argument of type 'bool' is not iterable
```
# Why it fails
`facts` is not reset after running `tests/test_assoccomm.py::test_assoccomm_objects` with `bool` remaining.

# Fix
Clear `associative.facts` before `tests/test_assoccomm.py::test_eq_assoccomm`.

2021-11-15 22:54 UTC, brandonwillard requested changes
Thanks for pointing this out!

Just to make sure we're completely clear of the issue, let's use a `pytest.fixture` (and remove all manual `*.clear()` calls).

Something like this should work:
```python
@pytest.fixture(autouse=True)
def clear_assoccomm():
    commutative.index.clear()
    commutative.facts.clear()
    associative.index.clear()
    associative.facts.clear()
    yield
```

Do you mind rebasing with a change to that effect?

2021-11-16 08:57 UTC, sturmianseq commented
Hi @brandonwillard, I changed the patch, please review the code changes, thank you!

2021-11-16 19:00 UTC, brandonwillard submitted a review, later dismissed

2021-11-17 00:47 UTC, brandonwillard commented
There were some `pre-commit` issues, so I fixed those and changed the fixture so that it essentially restores the original `Relation`s after each test.

2021-11-17 00:51 UTC, brandonwillard commented
Also, I noticed that the commit doesn't reference your @sturmianseq account.  If you want to change that, you can pull and then modify/rebase the commit.  If you don't want to change it, tell me and I'll merge this.

2021-11-17 00:52 UTC, brandonwillard approved these changes

2021-11-17 16:14 UTC, sturmianseq commented
Thanks for the reminder! I changed the author, please merge it.

2021-11-17 16:23 UTC, merged